"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Progress } from "@/components/ui/progress"
import { AlertCircle, Bot, User } from "lucide-react"

interface AIDetectionResult {
  aiProbability: number
  humanProbability: number
  confidence: string
  analysis: {
    perplexity: number
    burstiness: number
    patterns: string[]
  }
}

export function AIDetector() {
  const [text, setText] = useState("")
  const [isDetecting, setIsDetecting] = useState(false)
  const [result, setResult] = useState<AIDetectionResult | null>(null)
  const [error, setError] = useState<string | null>(null)

  const handleDetect = async () => {
    if (!text.trim()) {
      setError("Please enter text to analyze")
      return
    }

    setIsDetecting(true)
    setError(null)
    setResult(null)

    try {
      const response = await fetch("/api/ai-detect", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
      })

      if (!response.ok) {
        throw new Error("Failed to detect AI content")
      }

      const data = await response.json()
      setResult(data)
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred")
    } finally {
      setIsDetecting(false)
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>AI Content Detector</CardTitle>
        <CardDescription>Analyze text to detect if it was generated by AI</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <Alert>
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>
            AI detection is not 100% accurate. Use results as guidance, not definitive proof.
          </AlertDescription>
        </Alert>

        <Textarea
          placeholder="Paste text here to check if it was AI-generated..."
          value={text}
          onChange={(e) => setText(e.target.value)}
          rows={10}
          className="font-mono text-sm"
        />

        <div className="flex items-center gap-2">
          <Button onClick={handleDetect} disabled={isDetecting || !text.trim()}>
            <Bot className="h-4 w-4 mr-2" />
            {isDetecting ? "Analyzing..." : "Detect AI Content"}
          </Button>
          <span className="text-sm text-gray-500">{text.length} characters</span>
        </div>

        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {result && (
          <div className="space-y-4 mt-6">
            <div className="grid grid-cols-2 gap-4">
              <Card>
                <CardContent className="pt-6">
                  <div className="flex items-center gap-2 mb-2">
                    <Bot className="h-5 w-5 text-blue-600" />
                    <span className="font-semibold">AI-Generated</span>
                  </div>
                  <div className="text-3xl font-bold text-blue-600">{result.aiProbability}%</div>
                  <Progress value={result.aiProbability} className="h-2 mt-2" />
                </CardContent>
              </Card>

              <Card>
                <CardContent className="pt-6">
                  <div className="flex items-center gap-2 mb-2">
                    <User className="h-5 w-5 text-green-600" />
                    <span className="font-semibold">Human-Written</span>
                  </div>
                  <div className="text-3xl font-bold text-green-600">{result.humanProbability}%</div>
                  <Progress value={result.humanProbability} className="h-2 mt-2" />
                </CardContent>
              </Card>
            </div>

            <Alert>
              <AlertDescription>
                <strong>Confidence: {result.confidence}</strong>
                <br />
                {result.aiProbability >= 70
                  ? "This text likely contains AI-generated content."
                  : result.aiProbability >= 40
                    ? "This text may contain some AI-generated content."
                    : "This text appears to be primarily human-written."}
              </AlertDescription>
            </Alert>

            <Card>
              <CardHeader>
                <CardTitle className="text-base">Analysis Details</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                <div className="flex justify-between">
                  <span className="text-sm text-gray-600">Perplexity Score:</span>
                  <span className="text-sm font-medium">{result.analysis.perplexity.toFixed(2)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-sm text-gray-600">Burstiness Score:</span>
                  <span className="text-sm font-medium">{result.analysis.burstiness.toFixed(2)}</span>
                </div>
                {result.analysis.patterns.length > 0 && (
                  <div className="mt-3">
                    <span className="text-sm text-gray-600">Detected Patterns:</span>
                    <ul className="list-disc list-inside mt-1 text-sm">
                      {result.analysis.patterns.map((pattern, index) => (
                        <li key={index}>{pattern}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
